name: Publish to NPM
on:
  push:
    branches:
      - "main"
jobs:
  publish:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: chakra-ui-steps
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v1
        with:
          node-version: "18"
          registry-url: "https://registry.npmjs.org"
      - run: yarn

      - run: npm config set registry https://registry.npmjs.org && npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.npm_token }}
