name: Tests

on:
  pull_request_target:
    types:
      - opened
      - synchronize
      - reopened
    branches:
      - "develop"
    paths:
      - "chakra-ui-steps/**"

defaults:
  run:
    working-directory: chakra-ui-steps

jobs:
  Tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: yarn
      - name: Run test suite
        run: yarn test
